### ISSUE TITLE
Instruction take no effect on android app

### ISSUE THREAD

**Issue by rovkinmax** [VKCOM/vkompose#1]
I've added gradle plugin in to project like this 
`id("com.vk.vkompose") version "0.1"`

```
vkompose {
    skippabilityCheck {
        stabilityConfigurationPath = project.rootProject.rootDir.absolutePath + "/config/compose/compiler_config.conf"
        isEnabled = true
    }

    recompose {
        isHighlighterEnabled = true
        isLoggerEnabled = true
    }

    testTag {
        isApplierEnabled = true
        isDrawerEnabled = true
        isCleanerEnabled = true
    }

    sourceInformationClean = true
}
```

And inside Application class 
```
RecomposeLoggerConfig.isEnabled = true
RecomposeHighlighterConfig.isEnabled = true
TestTagDrawConfig.isEnabled = true

```

**Comment by 0xera** [comment]
Hi. What functionality you want to use?

Also you should add gradle plugin for every module with kotlin code where you want to use compiler plugins. 

I see you enable testTag generation and cleaning in same time. It is not correct way. 

Could you share sample project where i will be able to reprocude the issue?

**Comment by StalDenc** [comment]
Good afternoon, I have the same thing. I configured everything according to the instructions and did not see any results. I didn’t even fully understand what the final result should be. Parameter highlighting, logging?

`vkompose {
     skippabilityCheck {
         // For more see
         // https://android-review.googlesource.com/c/platform/frameworks/support/+/2668595
         // https://issuetracker.google.com/issues/309765121
         stabilityConfigurationPath = "${project.buildDir.absolutePath}/file.config"
         isEnabled = true
     }

    recompose {
        isHighlighterEnabled = true
        isLoggerEnabled = true
    }

    testTag {
        isApplierEnabled = true
        isDrawerEnabled = true
        isCleanerEnabled = false
    }

    sourceInformationClean = true
}`


` RecomposeLoggerConfig.isEnabled = true
        RecomposeHighlighterConfig.isEnabled = true
        TestTagDrawConfig.isEnabled = true`

**Comment by 0xera** [comment]
finally. i have reproduced the problem.

for workaround you can add plugins separately. For example
```
plugins {
    id("com.vk.recompose-highlighter") version "0.1"
    id("com.vk.recompose-logger") version "0.1"
    id("com.vk.compose-test-tag-applier") version "0.1"
    id("com.vk.compose-test-tag-cleaner") version "0.1"
    id("com.vk.compose-test-tag-drawer") version "0.1"
    id("com.vk.compose-source-information-cleaner") version "0.1"
    id("com.vk.composable-skippability-checker") version "0.1"
}
```

I am going to publish fixed version very soon. There was problem with races between my plugin and kotlin gradle plugin in afterEvaluate callback.

**Comment by 0xera** [comment]
Check please 0.2 version @rovkinmax @StalDenc

**Comment by StalDenc** [comment]
@0xera Everything works, thank you. Just could you share a description of the color schemes for the recompositions?

**Comment by 0xera** [comment]
@StalDenc of course. i took the highlighter from google samples https://github.com/android/snippets/blob/c381c783773ef6744f3fa810e29536876c9858d7/compose/recomposehighlighter/src/main/java/com/example/android/compose/recomposehighlighter/RecomposeHighlighter.kt#L80


Blue: We need at least one composition to draw, so draw the smallest border color in blue.
Green: 2 compositions is _probably_ okay.
Yellow..Red: 3 or more compositions before timeout may indicate an issue. lerp the color from yellow to red, and continually increase the border size.
