### ISSUE TITLE
Android studio plugin doesn't work with Android Studio Jellyfish | 2023.3.1 Patch 1

### ISSUE THREAD

**Issue by impossible1770** [VKCOM/vkompose#11]
After updating Android studio -> Jellyfish patch 1, the plugin stopped working and does not show all possible options when the parameter is not stable.

**Comment by 0xera** [comment]
I checked it. Everything works

**Comment by impossible1770** [comment]
For example:

1) If some data from another module doesn't have compose compile options or stable annotations, it is considered unstable, although the plugin shows no errors.
2) Some viewmodels are marked as stable by the plugin, but some are not. (before update all viewmodels were unstable)

Before the update, everything worked correctly.
**Plugin version:** 0.2.4-Jellyfish

**Comment by 0xera** [comment]
1. It is not. Classes from other modules can be considered as stable, unstable or runtime stable depending on the situation
2. Is ViewModel in different module? It seems to be considered as runtime stable. In previous versions of plugin there was a bug wich was fixed [here](https://github.com/VKCOM/vkompose/commit/6accf20de9e17ce86f4913c54553b865e07ada7d)
