### ISSUE TITLE
Functions with unstable paramaters: androidx.compose.ui.graphics.painter.Painter 

### ISSUE THREAD

**Issue by ltttttttttttt** [VKCOM/vkompose#12]
```
Functions with unstable paramaters:
com.lt.compose_views.chain_scrollable_component.scrollable_appbar.ScrollableAppBar:
	 (name=background, type=Parameter, class=androidx.compose.ui.graphics.painter.Painter, reason=Unstable(type Painter doesn't have @StabilityInferred))
```
	 
```kotlin
@Composable
fun ScrollableAppBar(
    title: String,
    background: Painter,
    modifier: Modifier = Modifier,
){}
```

How should classes provided by systems like Painter be handled? By using `stabilityConfigurationPath = "/path/file.config"` ?

**Comment by 0xera** [comment]
Hi. It looks strange because it should not report about classes from compose package. Could you say which version you are using?

**Comment by ltttttttttttt** [comment]
0.5.3-k2

**Comment by ltttttttttttt** [comment]
https://github.com/ltttttttttttt/ComposeViews/tree/dev
set vkomposeIsCheck = true
Then delete the outdated methods to reproduce them

**Comment by 0xera** [comment]
have found problem's origin here https://github.com/JetBrains/kotlin/commit/93af9f33e46ed7cdfed19da886f921afe2ae14cc

**Comment by 0xera** [comment]
try 0.5.4-k2

**Comment by ltttttttttttt** [comment]
This is effective
