### ISSUE TITLE
RecomposeLogger does not compile on Kotlin 2.0

### ISSUE THREAD

**Issue by Girrafeec** [VKCOM/vkompose#14]
https://github.com/VKCOM/vkompose/blob/60c84807fbf33c249972be4aa30ffe7f4ef407f1/compiler-plugin/recompose/logger/plugin/src/main/kotlin/com/vk/compiler/plugin/recompose/logger/RecomposeLogger.kt#L373

Reason: IrVarargImpl was moved to factory builder function (https://github.com/JetBrains/kotlin/blob/47ff19ff2f9c1df73754d6059143a4390f286677/compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/expressions/impl/builders.kt#L729)

Changes:
https://github.com/JetBrains/kotlin/commit/62f546ca0c8828628f8b0ff6af093686f7eeb996
https://github.com/JetBrains/kotlin/commit/826ae05f285c3eec91bcc5f8c08fe0ad0841cf39

**Comment by 0xera** [comment]
Could you share what versions of vkompose and kotlin you are using?

**Comment by Girrafeec** [comment]
Vkompose: 0.5.5
Kotlin: 2.0.0

**Comment by Girrafeec** [comment]
Changed version to 0.5.5-k2 and everything works fine. Closed.
