### ISSUE TITLE
Test tag for default modifier is not getting generated

### ISSUE THREAD

**Issue by kameshyadavky** [VKCOM/vkompose#19]
Hi loved your library and the test tag part is greatly appreciated, but I have one issue
```
Column() -> is not getting generated to 
Column(<default-value>.applyTestTag())
```

what i am seeing is 
`Column((Modifier)null)`

Is this intentional?

Compose version -> 1.6.7
Library version -> 0.6-k2

**Comment by 0xera** [comment]
Thanks for the report. Could you say which version of Kotlin you are using? And could you try 0.6.2-k2?

**Comment by kameshyadavky** [comment]
Yes tried with `0.6.2-k2` with Kotlin version 2.0.20, still same i have not updated compose version

**Comment by 0xera** [comment]
I checked. We can't extract the default value from compiled libraries, and the Column function example is wrong. But Column(Modifier) will work because here we know about the argument expression. I suggest you wrap the Column function block with your own function, e.g. 
```kotlin
fun YourFunc(modifier: Modifier = Modifier) {
   Column(modifier) {}
}
```
