### ISSUE TITLE
Hello, may I ask if this library will have an impact on the products of the project? For example, apk, exe, etc

### ISSUE THREAD

**Issue by ltttttttttttt** [VKCOM/vkompose#2]

**Comment by 0xera** [comment]
It depends on which feature you enable.

- skippability checks: has no effect
- recompose highlighter: adds additional modifier for all composable function call
- recompose logger: add additional function call that tracks recompositions for every composable function call
- test tag drawer by long tap: also adds additional modifier like recompose highlighter
- test tag applier: modify modifier argument and add set testTag for composable nodes
- test tag cleaner: just replace all testTag with empty string
- source information cleaner: remove sourceInformation function calls those need for layout Inspector. it is generated for debug build by default, but there is no way to disable it out of the box. 


So for release build i recommend to use this plugins:
- skippability checks
- test tag cleaner

You can also use other plugins if they dont have a big impact on size and performance of your app, but they can do.
