### ISSUE TITLE
AS plugin doesn't work

### ISSUE THREAD

**Issue by KatherineStrider** [VKCOM/vkompose#4]
The plugin does not work on either the hedgehog AS or the iguana AS. Most likely the reason is the incorrect path for the tag icon. Could you correct the path please?

**Comment by 0xera** [comment]
Oops. Could you try to disable testtag option if you dont need it? I will fix it as soon as possible 
https://github.com/VKCOM/vkompose/blob/master/art/vkompose-idea-plugin-preferences.png

**Comment by 0xera** [comment]
try this https://github.com/VKCOM/vkompose/blob/master/idea-plugin/vkompose-idea-plugin/vkompose-idea-plugin-0.1.1-Iguana.jar

**Comment by KatherineStrider** [comment]
Thanks, everything works now!

**Comment by 0xera** [comment]
You're welcome
