### ISSUE TITLE
Support applying gradle plugin inside Groovy script

### ISSUE THREAD

**Issue by ArTemmey** [VKCOM/vkompose#5]
Hello. Our app uses Groovy Gradle scripts. When we apply com.vk.vkompose plugin we have the following exception during the sync:
<img width="1542" alt="Снимок экрана 2024-01-26 в 17 53 49" src="https://github.com/VKCOM/vkompose/assets/35735328/1cab876b-f3f8-44bf-955c-499062450f9d">

**Comment by 0xera** [comment]
Seems strange. I will investigate it

**Comment by 0xera** [comment]
Could you share the example of build.gradle file with vkompose plugin?

**Comment by 0xera** [comment]
So, i think you apply plugin like this:
<img width="419" alt="Снимок экрана 2024-01-27 в 16 24 58" src="https://github.com/VKCOM/vkompose/assets/56160164/a8ad7d3d-27eb-41b9-9c5a-6f127679c565">

But implementation, api and other configurations are supplied by java plugin and cannot be used until java plugin is applied.

To apply vkompose plugin you should:
1.  add classpath dependency in your root build.gradle.kts
```groovy
buildscript {
    ext {
        compose_version = '1.5.4'
        kotlin_version = "1.9.10"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.0-beta02'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.vk.vkompose:com.vk.vkompose.gradle.plugin:0.3.2" // see here

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```
2.  apply vkompose plugin after kotlin and android plugins
```groovy
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.vk.vkompose'
```
3. configure vkompose plugin
```groovy
vkompose {

    setSkippabilityCheck(project, true)
    // or
    skippabilityCheck(project) {
        // For more see
        // https://android-review.googlesource.com/c/platform/frameworks/support/+/2668595
        // https://issuetracker.google.com/issues/309765121
//        it.stabilityConfigurationPath = "/path/file.config"
    }

    recompose(project) {
        it.isHighlighterEnabled = true
        it.isLoggerEnabled = true
    }

    testTag(project) {
        it.isApplierEnabled = true
        it.isDrawerEnabled = false
        it.isCleanerEnabled = false
    }

    setSourceInformationClean(project, true)
}
```


As soon as possible i will try to fix so that the order of plugins doesn't matter

**Comment by 0xera** [comment]
fixed in 0.4

**Comment by ArTemmey** [comment]
@0xera yes, sorry, that's my fault. I've called android plugin after vkompose. But anyway, after correcting this I get the following exception when configuring the plugin according to the documentation:
```Caused by: groovy.lang.MissingPropertyException: Could not set unknown property 'skippabilityCheck' for extension 'vkompose' of type com.vk.gradle.plugin.compose.utils.VkomposeExtension.```
Here is my build.gradle:
```
plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlinAndroid)
    id("com.vk.vkompose") version "0.3.2"
}

android {
    namespace 'com.example.test'
    compileSdk 34

    defaultConfig {
        minSdk 24
    }
}

vkompose {
    skippabilityCheck = true
    // or
    skippabilityCheck {
        // For more see
        // https://android-review.googlesource.com/c/platform/frameworks/support/+/2668595
        // https://issuetracker.google.com/issues/309765121
        stabilityConfigurationPath = "/path/file.config"
    }

    recompose {
        isHighlighterEnabled = true
        isLoggerEnabled = true
    }

    testTag {
        isApplierEnabled = true
        isDrawerEnabled = false
        isCleanerEnabled = false
    }

    sourceInformationClean = true
}
```

**Comment by ArTemmey** [comment]
@0xera Thank you very much! Now it works.
