### ISSUE TITLE
detekt plugin is not working

### ISSUE THREAD

**Issue by ArTemmey** [VKCOM/vkompose#6]
Hello. We have issue with vkompose detekt plugin integration. Even though vkcompose gradle plugin finds skippability problems and causes a compilation error, detekt plugin does not find them and detekt task passes without errors.

**Comment by 0xera** [comment]
Hi. As described [here](https://detekt.dev/docs/gettingstarted/type-resolution/#enabling-on-an-android-project) you should use `detekt<Variant>` task. For example, `detektDebug`

**Comment by ArTemmey** [comment]
That was helpful, thanks!
