### ISSUE TITLE
Parameter: Unstable(recursive analyse ImmutableList)

### ISSUE THREAD

**Issue by egorikftp** [VKCOM/vkompose#8]
plugin version: v0.4.2
Android Studio Iguana

Small reproducer

```kotlin
data class State(val data: ImmutableList<Item>)
data class Item(val title: String, val images: ImmutableList<String>)

@Composable
fun StateRender(state: State) {
    Text(text = state.data.toString())
}
```

<img width="736" alt="image" src="https://github.com/VKCOM/vkompose/assets/16294951/3d0c7651-f7ab-443d-9a6a-c83947f69079">

**Comment by 0xera** [comment]
similar to https://issuetracker.google.com/issues/327643787

**Comment by egorikftp** [comment]
But we use https://github.com/Kotlin/kotlinx.collections.immutable, not regular `List`

**Comment by 0xera** [comment]
List that is declared in stability configuration file and ImmutableList are being handle similarly. Anyway, try to check that case with new version :) 
https://github.com/VKCOM/vkompose/blob/master/idea-plugin/vkompose/vkompose-0.2.2-Iguana.jar

**Comment by egorikftp** [comment]
Thanks for quick update, now works as expected 🙂
