### ISSUE TITLE
Multi-module class stability

### ISSUE THREAD

**Issue by egorikftp** [VKCOM/vkompose#9]
Steps to reproduce:

1. create compose library module
2. define some stable state object (we assume it should be stable 🙂 )
```kotlin
data class TestState(val name: String)
```

3. connect with app module and observe plugin stability warning
```kotlin
@Composable
private fun TopBanner(state: TestState) {
    Text(text = "Hello ${state.name}!")
}

```
<img width="600" alt="Screenshot 2024-04-25 at 17 15 16" src="https://github.com/VKCOM/vkompose/assets/16294951/c63b967b-236d-4c7c-bd78-2664fcb02b57">

Sample project: https://github.com/egorikftp/StabilityIssue

**Comment by 0xera** [comment]
Hi. Thanks for report. Try [vkompose-0.2.3](https://github.com/VKCOM/vkompose/blob/master/idea-plugin/vkompose/)

**Comment by egorikftp** [comment]
Looks fixed 🙂
